import React from "react";

function Contest() {
  return (
    <div className="contest">
      <h2>
        MYNFT TWITTER CONTEST <br /> OFFICIAL RULES
      </h2>

      <ol>
        <li>
          <h4>OVERVIEW</h4>
          <p>
            The objective of this competition is to bring together interested
            members of the community to spread awareness and engagement for the
            non-fungible token <strong>("NFT")</strong> ownership verification
            services provided by the MyNFT.fyi application(the “
            <strong>MYNFT App</strong>”).
            <p></p>
            <p>
              Entrants will compete against each other, with the winner chosen
              randomly by the project sponsor.
            </p>
          </p>
        </li>
        <li>
          <h4> SPONSOR </h4>
          <p>
            These Official Rules (“Rules”) govern the operation of the MyNFT
            Twitter Contest (the “Contest”).{" "}
            <a
              href="https://DeFi.org"
              target="_blank"
              rel="noopener noreferrer"
            >
              DeFi.org
            </a>{" "}
            is the Contest sponsor (the <strong>"Contest Sponsor"</strong>).
          </p>
        </li>
        <li>
          <h4>DEFINITIONS</h4>
          <p>
            In these Rules, “ “we”, “our”, and “us” refer to the Contest Sponsor
            and “you” and “yourself” refers to a Contest participant. By
            entering you agree (individually or as a representative of your
            company) to be bound by these rules.
          </p>
        </li>
        <li>
          <h4>ENTRY PERIOD</h4>
          <p>
            The Contest starts at [______] a.m. Eastern Time (ET) on October 14,
            2021, and ends at 11:59 p.m. ET on December 31, 2021 (the
            <strong> "Submission Deadline"</strong>). If, by the Submission
            Deadline, there have not been at least [1,000] eligible entries, the
            contest will be ended with no winner. If there are [1,000] or more
            eligible entries, we will move on to selecting winners.
          </p>
        </li>
        <li>
          <h4>ELIGIBILITY</h4>
          <p>To participate: </p>
          <ul>
            <li>You must be at least 18 years of age or older.</li>
            <li>
              You must have an account on Twitter that has had at least 100
              followers for at least six months prior to the entry period (an
              <strong> "Eligible Twitter Account"</strong>).
            </li>
            <li>
              You must own an NFT that is used as the profile picture on your
              Eligible Twitter Account
            </li>
            <li>
              You must complete all of the actions set forth in Section 6 and
              your entry must be eligible under Section 7.{" "}
            </li>
          </ul>

          <p>
            Employees and directors of Contest Sponsor and its subsidiaries,
            affiliates and advertising agencies are not eligible, nor are
            persons involved in the execution or administration of this
            promotion, or the family members of each of the above (parents,
            children, siblings, spouse/domestic partners, or individuals
            residing in the same household). Void in any country that is subject
            to comprehensive sanctions, including Cuba, Iran, Lebanon, North
            Korea, the Crimean Region of the Ukraine, and Syria and where
            prohibited.
          </p>
          <p>
            If you are participating in your capacity as an employee, it is your
            sole responsibility to comply with your employer’s gift policies. We
            will not be party to any disputes or actions related to this matter.
            We are committed to complying with government gift and ethics rules
            and therefore government and public sector employees are not
            eligible to enter.
          </p>
        </li>
        <li>
          <h4>HOW TO ENTER</h4>
          <p>To enter, you must take the following steps:</p>
          <ul>
            <li>Follow @mynft_FYI on Twitter. </li>
            <li>
              Verify the NFT used as the profile picture on your Eligible
              Twitter Account on the MyNFT App at{" "}
              <a href="https://mynft.fyi/." target="_blank" rel="noreferrer">
                https://mynft.fyi/.
              </a>
            </li>
            <li>
              Tweet out the Certificate of Ownership generated by the MyNFT App.
            </li>
            <li>
              Add the verification link to the bio of your Eligible Twitter
              Account.
            </li>
            <li>
              Confirm and verify your participation at the following Google
              Form: [URL].{" "}
            </li>
          </ul>
        </li>
        <li>
          <h4>ELIGIBLE ENTRY </h4>
          <p>
            To be eligible, an entry must meet the following content/technical
            requirements:
          </p>
          <ul>
            <li>
              Entrants are only permitted to enter with one Twitter account, and
              anyone using multiple accounts or sock puppets is disqualified.
            </li>
            <li>
              Entrants warrant that their entry does not violate applicable law
              or the privacy, intellectual property rights, or other rights of
              any other person or entity; and
            </li>
            <li>
              The NFT you provide certification for as part of your entry may
              NOT contain, as determined by us in our sole and absolute
              discretion, any content that is obscene or offensive, violent,
              defamatory, disparaging or illegal, or that promotes alcohol,
              illegal drugs, tobacco or a particular political agenda, or that
              communicates messages that may reflect negatively on our goodwill.
            </li>
          </ul>
        </li>
        <li>
          <h4>USE OF ENTRIES </h4>
          <p>
            We are not claiming ownership rights to your Submission. However, by
            submitting an entry, you grant us an irrevocable, royalty-free,
            worldwide right and license to use, review, assess, test and
            otherwise analyze your entry and all its content in connection with
            this Contest and feature your entry and all content in connection
            with our marketing, sale, or promotional activities, including those
            relating to this Contest, in all media (now known or later
            developed). You will not receive any compensation or credit for use
            of your entry, other than what is described in these Rules. By
            entering you acknowledge that the we may have developed or
            commissioned materials similar or identical to your entry and you
            waive any claims resulting from any similarities to your entry.
            Further, you understand that we will not restrict work assignments
            of representatives who have had access to your entry and you agree
            that use of information in the development or deployment of our
            products or services does not create liability for us under this
            agreement or copyright or trade secret law. We are not obligated to
            use your entry for any purpose, even if it has been selected as a
            winning entry.
          </p>
        </li>
        <li>
          <h4>WINNER SELECTION AND NOTIFICATION</h4>
          <p>Winner Selection will follow the following procedures:</p>
          <ul>
            <li>
              {" "}
              If there are fewer than [1,000] eligible participants, the contest
              will end at the Submission Deadline.
            </li>
            <li>
              If there are more than 1,000 eligible participants, one eligible
              participant will be selected at random to receive the Grand Prize
              (as defined below).
            </li>
          </ul>
        </li>
        <li>
          <h4>PRIZES</h4>
          <p>
            The winner will receive the following NFT: Pudgy Penguin #522,
            located at
            <a
              href="https://opensea.io/assets/0xbd3531da5cf5857e7cfaa92426877b022e612cf8/5222"
              target="_blank"
              rel="noopener noreferrer"
            >
              {` https://opensea.io/assets/0xbd3531da5cf5857e7cfaa92426877b022e612cf8/5222`}
            </a>{" "}
            (the <strong> "Grand Prize"</strong>).  If the Grand Prize becomes
            unavailable for any reason, Contest Sponsor in its sole and absolute
            discretion may substitute a prize of like or equal value.
          </p>
          <p>
            By participating, you confirm that you understand that the value of
            the Grand Prize is subject to significant volatility.{" "}
          </p>
        </li>
        <li>
          <h4>ODDS</h4>
          <p>
            The odds of winning are based on the number of eligible entries
            received.
          </p>
        </li>
        <li>
          <h4>GENERAL CONDITIONS AND RELEASE OF LIABILITY</h4>
          <p>
            TO THE EXTENT ALLOWED BY LAW, BY ENTERING THE CONTEST YOU AGREE TO
            RELEASE AND HOLD HARMLESS THE CONTEST SPONSOR AND ITS PARENTS,
            PARTNERS, SUBSIDIARIES, AFFILIATES, EMPLOYEES AND AGENTS FROM ANY
            AND ALL LIABILITY OR ANY INJURY, LOSS OR DAMAGE OF ANY KIND
             (INCLUDING DIRECT, INDIRECT, INCIDENTAL, CONSEQUENTIAL OR PUNITIVE
            DAMAGES) ARISING IN CONNECTION WITH THIS CONTEST OR ANY PRIZE WON.
            WITHOUT LIMITING THE FOREGOING, BY PARTICIPATING IN THE CONTEST, YOU
            AGREE THAT THE CONTEST SPONSOR AND ITS PARENTS, PARTNERS,
            SUBSIDIARIES, AFFILIATES, EMPLOYEES AND AGENTS HAVE NO LIABILITY
            WHATSOEVER FOR ANY LIABILITY, ILLNESS, INJURY, DEATH, LOSS,
            LITIGATION, CLAIM, OR DAMAGE THAT MAY OCCUR, DIRECTLY OR INDIRECTLY,
            WHETHER CAUSED BY NEGLIGENCE OR NOT, FROM: (I) YOUR PARTICIPATION IN
            THE CONTEST AND/OR YOUR ACCEPTANCE, POSSESSION, USE, OR MISUSE OF
            ANY PRIZE OR ANY PORTION THEREOF; (II) TECHNICAL FAILURES OF ANY
            KIND, INCLUDING BUT NOT LIMITED TO THE MALFUNCTION OF ANY COMPUTER,
            CABLE, NETWORK, HARDWARE, OR SOFTWARE, OR OTHER MECHANICAL
            EQUIPMENT; (III) THE UNAVAILABILITY OR INACCESSIBILITY OF ANY
            TRANSMISSIONS, TELEPHONE, OR INTERNET SERVICE; (IV) UNAUTHORIZED
            HUMAN INTERVENTION IN ANY PART OF THE ENTRY PROCESS OR THE CONTEST;
            (V) ELECTRONIC OR HUMAN ERROR IN THE ADMINISTRATION OF THE CONTEST
            OR THE PROCESSING OF ENTRIES. YOU ACKNOWLEDGE AND AGREE THAT THE
            CONTEST SPONSOR HAS NOT MADE ANY WARRANTY, REPRESENTATION OR
            GUARANTEE EXPRESS OR IMPLIED, IN FACT OR IN LAW, WITH RESPECT TO THE
            PRIZE(S), INCLUDING, WITHOUT LIMITATION, TO SUCH PRIZE’S QUALITY OR
            FITNESS FOR A PARTICULAR PURPOSE.{" "}
          </p>
          <p>
            We will not be liable for technical, hardware, or software failures
            of any kind or lost or unavailable network connections that may
            limit or prohibit an eligible entrant’s ability to participate in
            the Contest.
          </p>
          <p>
            Our decisions are final and binding. We reserve the right in our
            sole discretion to disqualify any individual who is found to be
            tampering with the entry process or the operation of the Contest, to
            be acting in violation of these Terms and Conditions, or to be
            acting in an unsportsmanlike or disruptive manner, or with the
            intent to disrupt or undermine the legitimate operation of the
            Contest, or to annoy, abuse, threaten or harass any other person,
            and Sponsors reserve the right to seek damages and other remedies
            from any such person to the fullest extent permitted by law.
          </p>
          <p>
            We reserve the right to cancel, change or suspend this Contest for
            any reason, including cheating, technology failure, catastrophe, war
            or any other unforeseen or unexpected event that affects the
            integrity of this Contest, whether human or mechanical. If the
            integrity of the Contest cannot be restored, we may select winners
            from among all eligible entries received before we had to cancel,
            change or suspend the Contest. Rules violators will be prosecuted to
            the full extent of the law and may be banned from participation in
            the Contest.
          </p>
        </li>
        <li>
          <h4>GOVERNING LAW</h4>
          <p>
            GOVERNING LAW This Contest will be governed by the laws of the State
            of Israel, and you consent to the exclusive jurisdiction and venue
            of the courts of the State of Israel for any disputes arising out of
            this Contest. Further, in any such dispute, under no circumstances
            shall participant be permitted to obtain awards for, and hereby
            waives all rights to, punitive, incidental, or consequential
            damages, including reasonable attorney’s fees, other than
            participant’s actual out-of-pocket expenses (i.e. costs associated
            with entering this Contest). Participant further waives all rights
            to have damages multiplied or increased.
          </p>
        </li>
        <li>
          <h4>WINNER ANNOUNCEMENT</h4>
          <p>
            If there are more than 1,00 eligible entries, the winner will be
            announced within 30 days of the Submission Deadline.{" "}
          </p>
        </li>
      </ol>
    </div>
  );
}

export default Contest;
