export const EVENTS = {
  homePageLoad: "HOME_PAGE_LOADED",
  verifyAssetFromHomePageButtonClick: "VERIFY_BUTTON_FROM_HOME_PAGE_CLICK",
  verifyPageLoaded: "VERIFY_PAGE_LOADED",
  startVerificationButton: "START_VERIFICATION_BUTTON_CLICK",
  fecthNftButtonClick: "FETCH_NFT_CLICK",
  fetchNftFailed: "FETCH_NFT_FAILED",
  fetchNftNextStepClick: "FETCH_NFT_NEXT_CLICK",
  connectWallet: "CONNECT_WALLET_CLICK",
  connectWalletnextStepClick: "CONNECT_WALLET_NEXT_CLICK",
  signWithMetamaskClick: "WEB3_SIGN_CLICK",
  signWithMetamaskFailed: "WEB3_SIGN_FAILED",
  signWithMetamaskNextStepClick: "WEB3_SIGN_NEXT_CLICK",
  sendTweetClick: "SEND_TWEET_CLICK",
  doneClick: "VERIFICATION_DONE_CLICK",
  verifyPagePendingTriggerdAfterTSendingweet:
    "VERIFY_PAGE_PENDING_TRIGGERED_AFTER_SENDING_TWEET",
  verifyPagesuccessfullyVerified: "VERIFY_PAGE_SUCCESSFULLY_VERIFIED",
  certificatePageLoaded: "CERTIFICATE_PAGE_LOADED",
  certificateFetchFailed: "CERTIFICATE_FETCH_FAILED",
  assetOwnerFetchFailed: "ASSET_OWNER_FETCH_FAILED",
  openVerifySignatureModalClicked: "OPEN_VERIFY_SIGNATURE_MODAL_CLICKED",
  verifySignatureClicked: "VERIFY_SIGNATURE_CLICKED",
  verifyAssetFromCertificatePageButtonClick:
    "VERIFY_BUTTON_FROM_CERTIFICATE_PAGE_CLICK",
};
